// This file is generated by Gemini.
'use server';
/**
 * @fileOverview A landing page headline generator AI agent.
 *
 * - generateLandingPageHeadline - A function that handles the headline generation process.
 * - GenerateLandingPageHeadlineInput - The input type for the generateLandingPageHeadline function.
 * - GenerateLandingPageHeadlineOutput - The return type for the generateLandingPageHeadline function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateLandingPageHeadlineInputSchema = z.object({
  businessDescription: z
    .string()
    .describe('The description of the business for which the landing page is being created.'),
  targetAudience: z.string().describe('The target audience for the landing page.'),
  keywords: z.string().describe('Keywords related to the business or landing page.'),
});
export type GenerateLandingPageHeadlineInput = z.infer<
  typeof GenerateLandingPageHeadlineInputSchema
>;

const GenerateLandingPageHeadlineOutputSchema = z.object({
  headline: z.string().describe('A compelling headline for the landing page.'),
});
export type GenerateLandingPageHeadlineOutput = z.infer<
  typeof GenerateLandingPageHeadlineOutputSchema
>;

export async function generateLandingPageHeadline(
  input: GenerateLandingPageHeadlineInput
): Promise<GenerateLandingPageHeadlineOutput> {
  return generateLandingPageHeadlineFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateLandingPageHeadlinePrompt',
  input: {schema: GenerateLandingPageHeadlineInputSchema},
  output: {schema: GenerateLandingPageHeadlineOutputSchema},
  prompt: `You are an expert copywriter specializing in creating high-converting headlines for landing pages.

  Generate a compelling headline for a landing page based on the following information:

  Business Description: {{{businessDescription}}}
  Target Audience: {{{targetAudience}}}
  Keywords: {{{keywords}}}

  The headline should be concise, attention-grabbing, and relevant to the business and target audience.
  It should also incorporate the provided keywords where appropriate to improve SEO.
  The headline should be no more than 15 words.
  The headline should be in Spanish.

  Headline:`,
});

const generateLandingPageHeadlineFlow = ai.defineFlow(
  {
    name: 'generateLandingPageHeadlineFlow',
    inputSchema: GenerateLandingPageHeadlineInputSchema,
    outputSchema: GenerateLandingPageHeadlineOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
