'use server';
// This file is generated by Gemini.
import { initializeApp, getApps, App } from 'firebase-admin/app';
import { getFirestore, Timestamp } from 'firebase-admin/firestore';
import { credential } from 'firebase-admin';
import serviceAccount from '../../serviceAccountKey.json';

// Initialize Firebase Admin SDK if not already initialized
let app: App;
if (!getApps().length) {
    app = initializeApp({
        credential: credential.cert(serviceAccount)
    });
} else {
    app = getApps()[0];
}


const db = getFirestore(app);

interface SubscriptionPlan {
  id: string;
  name: string;
  description: string;
  price: number;
  currency: 'COP' | 'USD';
  billingPeriod: 'monthly' | 'yearly';
  features: string[];
  order: number;
  isActive: boolean;
  isPopular: boolean;
  createdAt?: Timestamp;
  updatedAt?: Timestamp;
}

/**
 * Fetches all active subscription plans from Firestore.
 * @returns A promise that resolves to an array of subscription plans.
 */
export async function getSubscriptionPlans(): Promise<Omit<SubscriptionPlan, 'id' | 'createdAt' | 'updatedAt' | 'isActive' | 'isPopular' | 'order'>[]> {
  try {
    const plansRef = db.collection('subscriptionPlans');
    const snapshot = await plansRef.where('isActive', '==', true).get();

    if (snapshot.empty) {
      console.log('No active subscription plans found.');
      return [];
    }

    const plans = snapshot.docs
        .map(doc => {
            const data = doc.data() as SubscriptionPlan;
            return {
                name: data.name,
                price: data.price,
                billingPeriod: data.billingPeriod,
                features: data.features,
                currency: data.currency,
                description: data.description,
                order: data.order // Incluimos order temporalmente para ordenar
            };
        })
        .sort((a, b) => a.order - b.order) // Ordenamos en memoria
        .map(({ order, ...plan }) => plan); // Removemos order del resultado final

    return plans;
  } catch (error) {
    console.error("Error fetching subscription plans:", error);
    return [];
  }
}
