// This file is generated by Gemini.
import { initializeApp, getApps } from 'firebase-admin/app';
import { getFirestore, Timestamp } from 'firebase-admin/firestore';

// Initialize Firebase Admin SDK if not already initialized
if (!getApps().length) {
  initializeApp();
}

const db = getFirestore();

interface SubscriptionPlan {
  id: string;
  name: string;
  description: string;
  price: number;
  currency: 'COP' | 'USD';
  billingPeriod: 'monthly' | 'yearly';
  features: string[];
  order: number;
  isActive: boolean;
  isPopular: boolean;
  createdAt?: Timestamp;
  updatedAt?: Timestamp;
}

/**
 * Fetches all active subscription plans from Firestore.
 * @returns A promise that resolves to an array of subscription plans.
 */
export async function getSubscriptionPlans(): Promise<Omit<SubscriptionPlan, 'id' | 'createdAt' | 'updatedAt' | 'isActive' | 'isPopular' | 'order'>[]> {
  try {
    const plansRef = db.collection('subscriptionPlans');
    const snapshot = await plansRef.where('isActive', '==', true).orderBy('order').get();

    if (snapshot.empty) {
      console.log('No active subscription plans found.');
      return [];
    }

    const plans = snapshot.docs.map(doc => {
        const data = doc.data() as SubscriptionPlan;
        // Return only the fields relevant for the AI tool
        return {
            name: data.name,
            price: data.price,
            billingPeriod: data.billingPeriod,
            features: data.features,
            currency: data.currency,
            description: data.description,
        };
    });

    return plans;
  } catch (error) {
    console.error("Error fetching subscription plans:", error);
    // In case of an error, return an empty array to prevent the AI from failing.
    // The AI will then inform the user that it couldn't retrieve the plans.
    return [];
  }
}
